### ISSUE TITLE
Node.js 12 actions are deprecated.

### ISSUE THREAD

**Issue by chrillep** [MrSquaare/ssh-setup-action#36]
## Issue
Node.js 12 actions are deprecated.

### Description
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: MrSquaare/ssh-setup-action

**Comment by MrSquaare** [comment]
Thanks for the report! I'll take care of it tomorrow

**Comment by wei18** [comment]
Same issue lol.
Thanks for taking time on this issue, @MrSquaare.

**Comment by MrSquaare** [comment]
Hello @chrillep and @Wei18! This should be fixed :smile: 

Use `MrSquaare/ssh-setup-action@v2` (or `MrSquaare/ssh-setup-action@v2.0.0`)

**Comment by chrillep** [comment]
ty looking at it now

**Comment by chrillep** [comment]
yep yep works! 🚀
