### ISSUE TITLE
Feature Request: Expose SSH_PATH, SSH_AGENT_PID & SSH_AUTH_SOCK as github outputs

### ISSUE THREAD

**Issue by vyas-n** [MrSquaare/ssh-setup-action#42]
## Issue

In this line: https://github.com/MrSquaare/ssh-setup-action/blob/1fa45168b92dca4fbb5a66fd7b74fd740fe6ed69/src/index.ts#L181C19-L181C19

The variables SSH_PATH, SSH_AGENT_PID & SSH_AUTH_SOCK are all exported as environment variables.

I'd like for these to also be exported as task variables so that I can pass them between tasks.

### Description

Currently, I'm using the https://github.com/docker/build-push-action#inputs action and it only support passing SSH information using the inputs to the job (it doesn't check environment variables on the host).

I would like a way to reference the Socket that this action creates.

**Comment by MrSquaare** [comment]
Hello!

Sorry for the (very) long response time. I've been particularly busy lately.

~~If I understand correctly, what you need is outputs from this action?~~ The issue title is pretty clear haha :sweat_smile: 

You can [transform an environment variable into an output](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs) via an intermediate step.

However, for your convenience, I'll also define outputs for each exported variable :)

**Comment by MrSquaare** [comment]
@vyas-n Available on `v2.1.0` (or `v2`)! Outputs are `ssh-path`, `ssh-agent-pid` and `ssh-auth-sock`
