### ISSUE TITLE
Getting `Private key is not set` error for some workflows when key exists

### ISSUE THREAD

**Issue by amrabed** [MrSquaare/ssh-setup-action#50]
## Issue
The workflow fails with a `private key not set` error while the key exists

### Description

I have the following in my workflow file:
```github
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
```

What I see in the workflow run is different though:
```
Run MrSquaare/ssh-setup-action@v3
  with:
    host: github.com
    private-key-name: id_rsa
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.8/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.8/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.8/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.8/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.8/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.8/x64/lib
Error: Error: Private key is not set
```

The `SSH_PRIVATE_KEY` secret exists and is being used successfully by other workflows using the same version of `ssh-setup-action`

![Screenshot 2024-03-22 at 11 50 13 AM](https://github.com/MrSquaare/ssh-setup-action/assets/3361565/c6eec706-9664-49f4-99f0-3fe5674ef5b2)

Any idea what might be causing this?

**Comment by MrSquaare** [comment]
Hello! It looks like the secret is empty or undefined. Are the other workflows in the same repository and running in the same context? What type of secret is it (repository or environment)? Can you restart this workflow with [debug logging](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging) enabled?

**Comment by amrabed** [comment]
I figured out what was causing the failure. The workflow was triggered from another workflow without inheriting the secrets. Thanks for your response though
